### ISSUE TITLE
section_order ignored 

### ISSUE THREAD

**Issue by spirritus** [saltstack-formulas/samba-formula#65]
If you specify section_order: ['global'] to only create the global entries for smb.conf this setting is ignored; global, printers and homes (in that order) are always created.

**Comment by myii** [comment]
@spirritus This could be due to this line:

https://github.com/saltstack-formulas/samba-formula/blob/a80fe6f95257edfabe784ebd9e1dbc46aff0416c/samba/files/smb.conf#L35

Which is `yes` by default:

https://github.com/saltstack-formulas/samba-formula/blob/778a00febba74ad9a0e6a5bc85839680ae1bb8f8/samba/defaults.yaml#L20

Have you tried setting this to `no` in your pillar as well as the change you mentioned above?

**Comment by spirritus** [comment]
He myii, thx for the info, salt is still a bit new to me. That line fixed it.

**Comment by spirritus** [comment]
Well, I guess it would be a better default. If you specify a list, then you would expect the list to define what is present and nothing else, unless you specify it with another parameter.
